name: Main Branch Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-apply:
    name: Apply Terraform Changes
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    uses: ./.github/workflows/terraform-apply.yml
    with:
      working_directory: infrastructure/cluster
    secrets: inherit
