name: Main Branch Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          github-token: ${{ secrets.github_token }}
          skip-git-pull: true
          git-push: false
          version-file: "version.yml"

      - name: Push Changelog
        run: |
          git config user.name "Conventional Changelog Action"
          git config user.email "conventional.changelog.action@github.com"
          git push

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

  terraform-apply:
    name: Apply Terraform Changes
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      matrix:
        module: [cluster, networking, argo-cd]
    uses: ./.github/workflows/terraform.yml
    with:
      working_directory: infrastructure/${{ matrix.module }}
    secrets: inherit
