name: Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  version:
    name: Version PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          github-token: ${{ secrets.github_token }}
          skip-git-pull: true
          git-push: false
          skip-commit: true
          skip-tag: true
          output-file: "false"
          version-file: "version.yml"

      - name: Comment on the Pull Request
        uses: hasura/comment-progress@v2.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: "jolfr/data-project-example"
          number: ${{ github.event.number }}
          id: version-comment
          message: ${{ steps.changelog.outputs.changelog }}
          recreate: true
