name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      working_directory:
        description: 'Directory containing Terraform configuration'
        required: true
        type: string
  workflow_call:
    inputs:
      working_directory:
        description: 'Directory containing Terraform configuration'
        required: true
        type: string

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    
    permissions:
      contents: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.2
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate
        
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        
      - name: Terraform Output
        id: output
        run: terraform output -json
        continue-on-error: true
        
      - name: Post Apply Summary
        run: |
          echo "### Terraform Apply Completed ✅" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Working Directory:** \`${{ inputs.working_directory }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Triggered By:** @${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "**Workflow:** \`${{ github.workflow }}\`" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ steps.output.outcome }}" == "success" ]; then
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "#### Infrastructure Outputs" >> $GITHUB_STEP_SUMMARY
            echo '```json' >> $GITHUB_STEP_SUMMARY
            echo "${{ steps.output.outputs.stdout }}" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi
